$(document).ready(function(){

    // Add CSS classes to <table> generated by Markdown
    var tables = $('table');
    $.each(tables, function(key, item) {
        $(item).addClass('table table-boxed');
    });

});